# Generated by Django 4.2.2 on 2023-08-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='image2',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='image3',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lat_news',
            name='image1',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lat_news',
            name='image2',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='nex_match',
            name='t1_img',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='nex_match',
            name='t2_img',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='score',
            name='a_im',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='score',
            name='h_im',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video2',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
