# Generated by Django 4.2.2 on 2023-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_image_alter_blog2_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lat_news',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video2',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
